# ==============================================================================
# 1. GLOBAL & APPLICATION IMAGE CONFIGURATION
# ==============================================================================
httpRoute:
  enabled: false
# Tổng số lượng bản sao (Pods) chạy đồng thời cho ứng dụng của bạn
replicaCount: 6
image:
  repository: esappsacr.azurecr.io/esapp-backend
  tag: e22926fe824ee0b6e4d9cf6a94d960d600092097
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
# ==============================================================================
# 2. DEPLOYMENT CONFIGURATION (Pods, Probes, Resources)
# ==============================================================================
podAnnotations: {}
podLabels: { app: esapp }
podSecurityContext: {}
securityContext: {}
# Cấu hình lượng tài nguyên CPU/RAM cấp phát cho mỗi Pod
resources: {}
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
metrics:
  enabled: false
# Bộ kiểm tra trạng thái hoạt động của ứng dụng (đang trỏ vào cổng HTTP chính)
livenessProbe:
  httpGet:
    path: /
    port: http # Sẽ map với tên cổng định nghĩa trong deployment.yaml
readinessProbe:
  httpGet:
    path: /
    port: http
# Tự động tăng giảm số lượng Pods dựa theo tải hệ thống
autoscaling:
  enabled: true
  minReplicas: 6
  maxReplicas: 31
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
# Hạ tầng điều phối Pod chạy trên Node nào
nodeSelector: {}
tolerations: []
affinity: {}
# ==============================================================================
# 3. NETWORKING CONFIGURATION (Service, Ingress, Gateway API)
# ==============================================================================

# --- KUBERNETES SERVICES ---
# Tách bạch rõ ràng giữa cổng chạy App và cổng xuất số liệu Metrics
service:
  type: ClusterIP
  port: 8080 # Cổng mà Service nội bộ lắng nghe cho App chính

# Cấu hình kết nối tới Azure Key Vault thông qua Secret Provider Class (CSI)
keyvault:
  name: "esapp-kv-staging"
  tenantId: "2dff09ac-2b3b-4182-9953-2b548e0d0b39"
  identityClientId: "37af957e-8e98-415d-8b9e-e0be24bbe02c"

secretsMapping:
  - azureName: "APP-KEY"
    envKey: "APP_KEY"

  - azureName: "MYSQL-ROOT-PASSWORD"
    envKey: "DB_PASSWORD"

  - azureName: "JWT-SECRET"
    envKey: "JWT_SECRET"

  - azureName: "GOOGLE-CLIENT-SECRET"
    envKey: "GOOGLE_CLIENT_SECRET"

  - azureName: "MYSQL-ADMIN-USERNAME"
    envKey: "DB_USERNAME"

  - azureName: "REDIS-PASSWORD"
    envKey: "REDIS_PASSWORD"
# Khai báo các Volume bổ sung nếu có ngoài luồng CSI mặc định
volumes: []
volumeMounts: []
# ==============================================================================
# 6. SECURITY ACCOUNTS
# ==============================================================================
