apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  APP_NAME: "esapp"
  APP_ENV: "development"
  APP_DEBUG: "true"
  APP_URL: "http://dev-api.20.247.224.41.nip.io"
  CORS_ALLOWED_ORIGINS: "http://dev.20.247.224.41.nip.io"

  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_HOST: "esapp-mysql-dev.mysql.database.azure.com"
  DB_PORT: "3306"
  DB_DATABASE: "esapp"
  DB_USERNAME: "azureuser"
  MYSQL_ATTR_SSL_CA: "/etc/ssl/certs/ca-certificates.crt"

  CACHE_STORE: "file"
  SESSION_DRIVER: "file"
  QUEUE_CONNECTION: "database"

  MAIL_MAILER: "smtp"
  MAIL_SCHEME: "smtp"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_FROM_ADDRESS: "no-reply@esapp.dev"

  JWT_ALGO: "HS256"
  GOOGLE_CLIENT_ID: "940152986387-hmnurcj182oerad7tik3d6pn26ib8ej9.apps.googleusercontent.com"
  GOOGLE_REDIRECT_URI: "http://dev.20.247.224.41.nip.io/auth/callback"
