apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev
type: Opaque
stringData:
  APP_KEY: "__FROM_KEYVAULT_APP_KEY__"
  DB_PASSWORD: "__FROM_KEYVAULT_DB_PASSWORD__"
  JWT_SECRET: "__FROM_KEYVAULT_JWT_SECRET__"
  GOOGLE_CLIENT_SECRET: "__FROM_KEYVAULT_GOOGLE_CLIENT_SECRET__"
  MAIL_USERNAME: "__FROM_KEYVAULT_MAIL_USERNAME__"
  MAIL_PASSWORD: "__FROM_KEYVAULT_MAIL_PASSWORD__"
