apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: frontend
    color: green           # ← This is very important
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http