




replicaCount: 6
autoscaling:
  enabled: true
  minReplicas: 6
  maxReplicas: 31
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

image:
  repository: esappsacr.azurecr.io/esapp-frontend


  pullPolicy: IfNotPresent

  tag: d2a4daa296db0c25a0fcc39ffa8becbaad0b4810


imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""


serviceAccount:

  create: true

  automount: true

  annotations: {}


  name: ""



podAnnotations: {}


podLabels: { app: esappfe }

podSecurityContext: {}


securityContext: {}








service:
  type: ClusterIP
  port: 80


ingress:
  enabled: false
  className: ""
  annotations: {}


  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []







httpRoute:

  enabled: false

  annotations: {}

  parentRefs:
    - name: gateway
      sectionName: http


  hostnames:
    - chart-example.local

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers
















resources: {}












livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http




volumes: []






volumeMounts: []




nodeSelector: {}

tolerations: []

affinity: {}
