apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://haproxytech.github.io/helm-charts
    chart: haproxy
    targetRevision: 1.52.0

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true