apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esapp
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/piracyiskey/Do-An-IS402.git
    targetRevision: main
    path: gitops/esapp

  destination:
    server: https://kubernetes.default.svc
    namespace: monitor-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true