apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 66.3.1
    helm:
      releaseName: monitor

      values: |
        prometheus:
          enabled: true

        alertmanager:
          enabled: true

        grafana:
          enabled: true

        kubeStateMetrics:
          enabled: true

        nodeExporter:
          enabled: true

        prometheusOperator:
          enabled: true


        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
