controller:
  service:
    type: LoadBalancer

    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz


  externalTrafficPolicy: Cluster

  publishService:
    enabled: true