controller:
  service:
    type: LoadBalancer

    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

  # important for Azure LB + AKS stability
  externalTrafficPolicy: Cluster

  publishService:
    enabled: true