apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "esappfe.fullname" . }}-config
  labels:
    {{- include "esappfe.labels" . | nindent 4 }}

data:
  VITE_GOOGLE_CLIENT_ID: "518525301067-6vci81s4s8eo4klif1rmj18rl8o216po.apps.googleusercontent.com"
  VITE_GOOGLE_REDIRECT_URI: "/auth/callback"
  VITE_BACKEND_API_URL: "http://fe.135.171.243.189.nip.io/api"