apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esappfe-ingress
  namespace: frontend-ns
spec:
  ingressClassName: nginx
  rules:
    - host: fe.57.155.223.9.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esappfe
                port:
                  number: 80
