apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "esapp.fullname" . }}
  labels:
    {{- include "esapp.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3


  selector:
    matchLabels:
      {{- include "esapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "esapp.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "esapp.fullname" . }}-config
            - secretRef:
                name: {{ include "esapp.fullname" . }}-secret
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "esapp.fullname" . }}-kv-provider




  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100