apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-esapp
  namespace: esapp
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEYVAULT_NAME}"
    tenantId: "${AZURE_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: app-key
          objectType: secret
        - |
          objectName: mysql-password
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: app-key
          key: APP_KEY
        - objectName: mysql-password
          key: DB_PASSWORD
        - objectName: redis-password
          key: REDIS_PASSWORD
